FROM eclipse-temurin:8-jdk as builder
WORKDIR extracted
ADD target/*.jar api-gateway.jar
RUN java -Djarmode=layertools -jar api-gateway.jar extract

FROM eclipse-temurin:8-jdk
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./
EXPOSE 9191
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]